version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17

    parallelism: 2

    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
